### ISSUE TITLE
How to exclude lod.calcs and calcs.union tests

### ISSUE THREAD

**Issue by GumpacG** [tableau/connector-plugin-sdk#1179]
**About You:**
Name: Guian Gumpac
Company: Improving

**Your question:**
How can I exclude lod.calcs and calcs.union tests? We have known database limitations and would like to exclude it from TDVT.

I've tried including lod.calcs to `ExpressionExclusions_Standard` list in `[StandardTests]` and `ExpressionExclusions_Standard` and `LogicalExclusions_Calcs` lists in `[LODTests]`.
I've tried including calcs.union to `LogicalExclusions_Calcs` list in `[StandardTests]` and `LogicalExclusions_Calcs` in `[UnionTest]`. Unfortunately, these didn't work.

**Comment by pvanderknyff** [comment]
Try the following:

```
[LODTests]
ExpressionExclusions_Calcs = lod.calcs

[UnionTest]
ExpressionExclusions_Standard = calcs.union
```

You can see the documentation on building the ini file here: https://tableau.github.io/connector-plugin-sdk/docs/tdvt#lodtests

**Comment by GumpacG** [comment]
Hi @pvanderknyff,

I've tried
```
[UnionTest]
ExpressionExclusions_Standard = calcs.union
```
and 
```
[UnionTest]
LogicalExclusions_Calcs = calcs.union
```
That didn't seem to work 
<img width="310" alt="Screenshot 2023-09-22 at 3 27 58 PM" src="https://github.com/tableau/connector-plugin-sdk/assets/29149268/c2cb37de-4cbe-4c6e-8c99-02775ee6cb04">
\
\
\
And regarding `lod.calcs`, whenever I add 
```
[LODTests]
ExpressionExclusions_Calcs = lod.calcs
``` 
and run tests, I get
```
No tests found for config [name=expression.lod.opensearch] [tds=cast_calcs.opensearch.tds] [exclusions=lod.calcs] [test pattern=exprtests/lodcalcs/setup.*.txt] [is_logical=False] [root_dir=/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/tdvt]
No tests found. Check arguments.
```

**Comment by pvanderknyff** [comment]
Turns out calcs.union is the only suite in [UnionTest] so just removing that section from the ini should work.

`ExpressionExclusions_Calcs = lod.calcs` should be working under the [LODTests] heading, we have examples of it internally that are passing. Once UnionTest is removed see if it works, and make sure there is only one [LODTests] heading in your ini file. Otherwise something strange is going on in your environment or test config that we'll have to dig into.

**Comment by GumpacG** [comment]
calcs.union was skipped once I removed [UnionTest] section however I still get that error for lod.calcs. Does ordering matter? Just wondering if there's other things I could try.
<img width="443" alt="Screenshot 2023-09-22 at 4 58 14 PM" src="https://github.com/tableau/connector-plugin-sdk/assets/29149268/3219ca9e-6514-4287-9cca-1ff77a4d6a53">

**Comment by pvanderknyff** [comment]
Sorry, should have been more clear. Remove the line under [UnioneTest] as well, so delete 
`ExpressionExclusions_Standard = calcs.union`
as well.

For the LODTests, ordering shouldn't matter I think. I've confirmed the test is skipped without error locally, and we have those exact lines for test suites we run in daily test runs. Can you paste the contents of your ini file here? I think it's something specific to your configuration or environment.

May also be worth making sure you've syncd with the main branch of the SDK to make sure you hsve the latest TDVT version.

**Comment by GumpacG** [comment]
I've updated tdvt to 2.7.5 and I still got the same output.

Thanks for looking into this, my ini is:
```
[Datasource]
Name = mydb
LogicalQueryFormat = simple_lower

[StandardTests]
ExpressionExclusions_Standard = 
    math.round.extended,
    string.contains.null,
    string.endswith.null,
    string.find.null,
    string.isdate,
    string.space.int.var,
    string.startswith.null,
    agg.max,
    agg.min,
    string.char,
    string.split.right,
    string.split,
    string.space.int.constant,
    string.space,
    operator.num
LogicalExclusions_Calcs = 
    BUGS.B27875-asc-nulls-first,
    Filter.QFilter-Null,
    Filter.QFilter-max-NotNull,
    Filter.QFilter-min-NotNull,
    join.null.bool,
    join.null.date,
    join.null.datetime,
    join.null.int,
    join.null.real,
    join.null.str,
    Filter.QFilter-NotNull,
    Filter.QFilter-max-Null,
    Filter.QFilter-min-Null,
    Filter.QFilter-minmax-NotNull,
    Filter.QFilter-minmax-Null,
    BUGS.B1713,
    Filter.TopN-context
LogicalExclusions_Staples =
    Query.Sort_Alphabetic_DESC_Top1,
    Query.Filter_SliceAggQUnaggQ_AxisQO,
    Query.HideEmptyRows,
    ZTesting.Staples9,
    BUGS.B340,
    Query.Unaggregated_Filter_NoDateTime,
    BUGS.B8888,
    Query.FilterBy_DateTime_Slices

[LODTests]
ExpressionExclusions_Calcs = lod.calcs

[ConnectionTests]
StaplesTestEnabled = True
CastCalcsTestEnabled = True
```

**Comment by pvanderknyff** [comment]
It looks like you've found a bug in the release version of TDVT. Skipping lod.calcs throws an error because there are no other calcs tests in the LOD suite. This bug seems to have been fixed, either explicitly or accidentally, in the internal TDVT we use, which we usually post to github coinciding with major Tableau releases. We're looking at either making a hotfix or making a full TDVT release to fix this bug.

However, I don't think waiting on that should block your connector review. Leave lod.calcs unskipped for now, once that and other feedback is addressed hopefully we can move to next steps.

Leaving this issue open until lod.calcs skipping bug is addressed.

**Comment by GumpacG** [comment]
Thanks @pvanderknyff!
